### ISSUE TITLE
Add playground for Android

### ISSUE THREAD

**Issue by imanishbarnwal** [appwrite/awesome-appwrite#13]
There's a missing playground of Android in README.md.

**Comment by Shivang0** [comment]
Update README.md #27

Added that in this pull request .

**Comment by imanishbarnwal** [comment]
> Update README.md #27
> 
> Added that in this pull request .

It's already been done in #14 you should check.

**Comment by eldadfux** [comment]
Merged #14

**Comment by Shivang0** [comment]
Ok cool .

**Comment by eldadfux** [comment]
You can explore any of our repos on the appwrite namespace.
