### ISSUE TITLE
🚀 Feature: adding more resources

### ISSUE THREAD

**Issue by tessamero** [appwrite/awesome-appwrite#480]
### 🔖 Feature description

Found quite a few links to how-to's/blogs that seemed helpful in a support query. Can you check and see if several of these are added: https://discord.com/channels/564160730845151244/1090593787295830136

### 🎤 Pitch

Thanks

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi
Thank you creating this. I will go through this.

**Comment by adityaoberai** [comment]
@tessamero the resource in the thread is Biswa's blog around his "No Signal" app
We already have all 3 parts as well as the app here in the repo.

Will ping the other folks to raise PRs for their projects here.
