### ISSUE TITLE
📚 Documentation: It's quite difficult to customize your own

### ISSUE THREAD

**Issue by LyVanBong** [appwrite/awesome-appwrite#488]
### 💭 Description

It's quite difficult to customize your own, hope you guys will add more documentation related to testing on docker swarm, k8s ... in addition, the components inside appwrite are also quite difficult to configure such as smtp, sms.....

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Also, please note that this repo is for showcasing the projects built with Appwrite, our main repo is : https://github.com/appwrite/appwrite

**Comment by LyVanBong** [comment]
issues fix done in discord appwrite
