### ISSUE TITLE
🐛 Bug Report: unable to create new collection

### ISSUE THREAD

**Issue by saidhasyim** [appwrite/awesome-appwrite#490]
### 👟 Reproduction steps

Add new collection in VSC. After inputting the collection name and press enter, it will show error: Param "collectionId" is not optional.

### 👍 Expected behavior

it should prompt for collectionId input

### 👎 Actual Behavior

it prompts error

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Something else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by adityaoberai** [comment]
@saidhasyim what resource are you using that cause this issue?

**Comment by saidhasyim** [comment]
Hello. I was using appwrite cloud.
