### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by nisharmultani** [appwrite/awesome-appwrite#491]
### 👟 Reproduction steps

I am starting to make the backend for a project so when I go to create an API model where I enter API key name  and choose Expiration Date and when I click on the next button it gives me the error " param name does not option"

### 👍 Expected behavior

step - 1 if i add both input field then its tack me to next page

step -  2 if my input data is not as formate then its give me proper error message or example 

### 👎 Actual Behavior

if I fill in both inputs then it tacks to the next page but it gives me an error

note :  if my input is wrong then its give me proper error message that you input is wrong or give me some example

![Screenshot from 2023-05-24 13-04-19](https://github.com/appwrite/awesome-appwrite/assets/52249398/d57a5a38-77bf-410b-83ab-7c410cdf65a2)
gives

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I am using Linux 18 version and use google chrome 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by adityaoberai** [comment]
@nisharmultani this repo is specifically for adding community-built Appwrite resources. For any Appwrite-related issues, please visit our [main repo](https://github.com/appwrite/appwrite)
