### ISSUE TITLE
🐛 Bug Report: The hactoberfest 2022 link is broken.

### ISSUE THREAD

**Issue by jaiakash** [appwrite/awesome-appwrite#502]
### 👟 Reproduction steps

Click on this https://github.com/appwrite/awesome-appwrite?tab=readme-ov-file#hacktoberfest-2022

### 👍 Expected behavior

It redirects to https://github.blog/release-radar-sept-2022

### 👎 Actual Behavior

It should redirect to https://github.blog/2022-10-28-release-radar-sept-2022/#appwrite-1-0

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Something else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by jaiakash** [comment]
If granted, i can raise a PR for same.

**Comment by adityaoberai** [comment]
Thanks for raising this issue. You can update the link.
