### ISSUE TITLE
🚀 Feature: Add hacktoberfest 2023 link

### ISSUE THREAD

**Issue by jaiakash** [appwrite/awesome-appwrite#503]
### 🔖 Feature description

We could add the HF 2023 blog link to this as well.

### 🎤 Pitch

Add https://appwrite.io/blog/post/hacktoberfest-2023

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by symaticvisuals** [comment]
Hey @jaiakash , I'm eager to contribute to the project. Could you please list out the deliverables I'll be working on? Thanks!

**Comment by adityaoberai** [comment]
Hi @jaiakash 
We'll be adding any Hacktoberfest-centric content on Appwrite shared by any of our partners in the future. 
Therefore, I'm closing this issue for now.
