### ISSUE TITLE
📚 Documentation: Fix Getting Started for Server link in README.md

### ISSUE THREAD

**Issue by mschandana16** [appwrite/awesome-appwrite#507]
### 💭 Description

The "Getting Started for Server" link under learning resources in README.md is broken and redirects too many times.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by mschandana16** [comment]
If granted permission and assigned this issue, I can raise a PR for the same.

**Comment by adityaoberai** [comment]
@mschandana16 thank you for raising this issue. We're already working on this edit and will push a fix soon.
