### ISSUE TITLE
📚 Documentation: Fix "Delete Appwrite Docker containers and volumes" link in README.md 

### ISSUE THREAD

**Issue by mschandana16** [appwrite/awesome-appwrite#508]
### 💭 Description

The link titled - "Delete Appwrite Docker containers and volumes" under Playgrounds and Snippets section in README.md is broken and leads to a 404 error.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by mschandana16** [comment]
If granted permission and assigned this issue, I can raise a PR for the same.

**Comment by adityaoberai** [comment]
Hi @mschandana16 
We had discovered this issue as well and will be fixing it in an upcoming PR
