### ISSUE TITLE
Help developers by writing a blog post about Appwrite🗞

### ISSUE THREAD

**Issue by Meldiron** [appwrite/awesome-appwrite#89]
# Introduction

Appwrite has been and always will be a tool for developers. To emphasize this, we want to create the **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to write a blog post about Appwrite. **It can be anything! A s**tory about your Appwrite journey, what concepts you learned by using Appwrite, guide how to connect Appwrite to `something`... You are limited only by your imagination. **It can be anywhere!** We accept submissions of articles on any well-known platform, whether it is Medium, Dev.to, HashNode or something else.

### Requirements:

- Your article has to be publicly available
- Your article must tag `appwrite` in any way (hashtag, embedded, link...)
- Your article must be at least 1000 words long
- Your article should look nice 👀 (use titles, subtitles, screenshots, images, gifs, or even memes)

### Task summary:

- [ ]  Write a blog post about Appwrite
- [ ]  Publish an article on your favorite platform or website (Medium, Dev.to, HashNod...)
- [ ]  Share the article on social media (Reddit / HackerNews / Twitter / Facebook / Other) - **optional**
- [ ]  Submit PR to [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite) with a link to your article

**This issue does not require assignment, and can be contributed by anyone! Just let us know you're working on it!**

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? Go ahead! We are accepting as many articles as the community can create. One note, **quality over quantity.**

**Happy Appwriting!**

**Comment by Vidushi-Gupta** [comment]
Hi, could you assign this to me? Thanks!

**Comment by Meldiron** [comment]
@Vidushi-Gupta We don't assign this issue. Go ahead, work on your blog post 😊 This issue is opened for everyone and we want as many quality PRs as our community can create.

**Comment by kambleaa007** [comment]
blogs seems awesome way to contribute, gimme a try building websites with AppWrite

**Comment by christyjacob4** [comment]
@kambleaa007 All the best :+1:

**Comment by Memphis1983** [comment]
I can still write a blog yes? I've been working on it but wanted to ask anyway to be sure.

**Comment by lohanidamodar** [comment]
@Memphis1983 Yes you can always write a blog post. All the best 🚀

**Comment by Meldiron** [comment]
To keep everything in one place, we decided to close this issue 😇 For any further activity, please visit exactly the same issue on our main repository: https://github.com/appwrite/appwrite/issues/1774
