### ISSUE TITLE
Upgrade our issue templates to use GitHub issue forms ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/awesome-appwrite#91]
# Introduction

GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

Appwrite currently uses the older [issue template format](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). Your task is to create **GitHub issue forms** for this repository. Please use [Appwrite's issue templates](https://github.com/appwrite/appwrite/tree/master/.github/ISSUE_TEMPLATE) as a reference for this PR.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Prepare **bug report** issue form in `.github/ISSUE_TEMPLATE/bug.yaml`
- [ ] Prepare **documentation** issue form in `.github/ISSUE_TEMPLATE/documentation.yaml`
- [ ] Prepare **feature request** issue form in `.github/ISSUE_TEMPLATE/feature.yaml`
- [ ] Push changes to **master** and test issue forms on your fork
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by Ln11211** [comment]
@Meldiron, I want to even work on this, and my october would be fun with updating documentation, I have previously requested to work on  "Upgrade our issue templates to use GitHub issue forms writing_hand #3 " and  "Upgrade our issue templates to use GitHub issue forms writing_hand #8" , as I thought why not go for three assignments ?(I will aslo do 4 if its allowed 🙃 ) .I will not dissapoint you.

**Comment by Meldiron** [comment]
@Ln11211 Assigned it to you! All the best 🚀

**Comment by Ln11211** [comment]
@Meldiron, I submited a pr but I can't find it anymore, and I actually completed it before @idivyanshbansal and I also tested the templates and uploaded the screenshots in my pr 😞. SO my pr won't be valid anymore ?

**Comment by idivyanshbansal** [comment]
> @Meldiron, I submited a pr but I can't find it anymore, and I actually completed it before @idivyanshbansal and I also tested the templates and uploaded the screenshots in my pr 😞. SO my pr won't be valid anymore ?

@Ln11211, they spam my request and close it. I will close it happily if they just tell me to close, but making spam makes me very disappointed. 😔

**Comment by lohanidamodar** [comment]
> @Meldiron, I submited a pr but I can't find it anymore, and I actually completed it before @idivyanshbansal and I also tested the templates and uploaded the screenshots in my pr disappointed. SO my pr won't be valid anymore ?

Please re-create the PR. We have not yet found your PR.

**Comment by Ln11211** [comment]
@Meldiron , https://github.com/appwrite/awesome-appwrite/pull/92#issue-747450089
here you go..

**Comment by adityaoberai** [comment]
Closing this issue since it has been resolved by #92
